### ISSUE TITLE
Allow config groups/nested use

### ISSUE THREAD

**Issue by Pistonight** [Pistonite/celer#115]
Originally this wasn't planned, but it seems too convenient and people will probably ask for it

```yaml
config:
- includes:
  - use: XXX
  - use: XXX
  - plugins:
      XXX
  plugins:
     XXX
```

There will be a hardcoded max depth, probably 16. using a `use` does not reset this depth

Error messages need to be redesigned. Currently they just take a config index:
```
Config at index X: XXXXX
```
An index trace is probably good enough
```
Config (trace=X,Y,Z): XXXXXX
```
