### ISSUE TITLE
Tags should be able to define different colors under light and dark background/themes

### ISSUE THREAD

**Issue by Pistonight** [Pistonite/celer#118]
Tags could do
```yaml
tags:
  foo:
    color:
      light: black # display as black in light background
      dark: white # display as white in dark background
    background:
      light: white
      dark: black
```

The themes will define which surfaces are light and dark and the correct color should be displayed accordingly
