### ISSUE TITLE
Bug: Links in notes are not transformed

### ISSUE THREAD

**Issue by Pistonight** [Pistonite/celer#124]
**Environment**
Browser: All

**Component**

Example: Document

**Description**

Example: Note blocks are not processed by the link plugin

**Reproduce**

Example: 
```yaml
route:
- section:
  - line:
      notes: .link(https://example.com)
```
Expected:
Link is clickable
Actual:
Link is not clickable
