### ISSUE TITLE
Improvement for movements

### ISSUE THREAD

**Issue by Pistonight** [Pistonite/celer#243]
- When `pop`ing, should not consider that step to put the icon. Put the icon in the step before popping
- should be able to use `push`, `pop`, and presets as part of `to`, for example:
```yaml
- to: pop
  exclude: true
- to: _SomePreset
  color: yellow
```
