### ISSUE TITLE
Support entry points other than project.yaml

### ISSUE THREAD

**Issue by Pistonight** [Pistonite/celer#62]
Useful in a monorepo setting where project.yaml may be in a sub path.

If user opens the sub path in web editor instead, the project cannot load files outside of the sub path.

So the solution is for celer to support configuring custom entry points

Proposal:
```yaml
# /project.yaml
entry-points:
- path/to/sub.yaml # name and path would be the same
- name: My Sub-project # have different path displayed in UI
  path: my/subproject.yaml
```

The entry-points property would be parsed by the wasm module to extract the entry points, and be available in the settings dialog for selection
The compiler will ignore it if it sees the property
